name: onestore_wallet_app
description: A Card Store for the OneStore App.
homepage: https://swingtechnologies.in/
repository: https://github.com/debojyoti452/onestore-app
issue_tracker: https://github.com/debojyoti452/onestore-app/issues

version: 1.2.1+5

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bot_toast: ^4.0.3
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  flutter_screenutil: ^5.6.1
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  json_annotation: ^4.8.0
  url_launcher: ^6.1.9
  encrypt_db: ^0.0.8

  ### DO-NOT MODIFY THIS LINE ###
  security_module: ^0.0.1
  
dev_dependencies:
  build_runner: ^2.3.3
  analyzer: ^5.4.0
  json_serializable: ^6.6.1
  dart_code_metrics: ^5.5.1
  freezed: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/card/
    - assets/logo/onestore_logo.png
