name: Manual Generate APK
on:
  workflow_dispatch:
    inputs:

      flavor:
        description: 'Which Flavor build?'
        required: true
        default: 'qa'

jobs:

  apk:
    name: Generate Release APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          distribution: 'zulu'
          cache: 'gradle'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false
          
      # Get flutter dependencies.
      - run: flutter clean

      # Get flutter dependencies.
      - run: flutter pub get

      # Create g.dart file.
#       - run: flutter pub run build_runner build --delete-conflicting-outputs
        
      # Create APK
      - name: Assemble app release APK
        run: flutter build apk
#         run: bash flutter build apk --release --flavor ${{ github.event.inputs.flavor }} -t lib/flavors/versions/${{ github.event.inputs.flavor }}.dart

      - name: Upload app APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          
                
      - name: Download app APK
        uses: actions/download-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
